# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amar's blog
email: amar@sanakal.com
description: Some thoughts and ramblings which may, at times, make some sense
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: AmarSanakal
github_username:  amar-sanakal
facebook_username:  amar.sanakal
timezone: Europe/London

# Build settings
markdown: kramdown
